
- name: Pull and run docker image
  hosts: localhost
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull krishnasharma46/scientific_calc:latest
      
    - name: run container
      shell: docker run -i -t --name calculator -d krishnasharma46/scientific_calc:latest